
# Reglage serveur
server:
  port: 10000
# nom appli
spring:
  application:
    name: gestionCours
  # Configuration BD
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: admin
      port: 27017
      host: localhost
      uri: mongodb://root:root@localhost:27017/admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration